# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grouped_mean <- function(x, group) {
    .Call(`_EquiTrends_grouped_mean`, x, group)
}

between_transformation <- function(x, group) {
    .Call(`_EquiTrends_between_transformation`, x, group)
}

matrix_between_transformation <- function(x, group) {
    .Call(`_EquiTrends_matrix_between_transformation`, x, group)
}

ols_cholesky <- function(XtX, Xty) {
    .Call(`_EquiTrends_ols_cholesky`, XtX, Xty)
}

double_demean <- function(x, individual, time, WD) {
    .Call(`_EquiTrends_double_demean`, x, individual, time, WD)
}

maxTestBoot_bootstrap <- function(Xb, X, B, variance, ID, period, WD, no_placebos) {
    .Call(`_EquiTrends_maxTestBoot_bootstrap`, Xb, X, B, variance, ID, period, WD, no_placebos)
}

maxTestBoot_wildbootstrap <- function(Xb, X, B, u_ddot, ID, period, no_placebos, WD) {
    .Call(`_EquiTrends_maxTestBoot_wildbootstrap`, Xb, X, B, u_ddot, ID, period, no_placebos, WD)
}

